<?
	$ItemInfo = array();
	
	$ItemInfo[] = array( name => "Пусто", color => '-1');
	$ItemInfo[] = array( name => "Скин: The Truth (ID:1)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Maccer (ID:2)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Andre (ID:3)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Barry ''Big Bear'' Thorne [Thin] (ID:4)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Barry ''Big Bear'' Thorne [Big] (ID:5)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Emmet (ID:6)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Taxi Driver/Train Driver (ID:7)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Janitor (ID:8)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:9)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Old Woman (ID:10)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Casino croupier (ID:11)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rich Woman (ID:12)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Street Girl (ID:13)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:14)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Mr.Whittaker (RS Haul Owner) (ID:15)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Airport Ground Worker (ID:16)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Businessman (ID:17)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Beach Visitor (ID:18)", color => '-1');
	$ItemInfo[] = array( name => "Скин: DJ (ID:19)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rich Guy ", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:21)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:22)", color => '-1');
	$ItemInfo[] = array( name => "Скин: BMXer (ID:23)", color => '-1');
	$ItemInfo[] = array( name => "Скин Madd Dogg Bodyguard: (ID:24)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Madd Dogg Bodyguard (ID:25)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Backpacker (ID:26)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Скин: Construction Worker (ID:27)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Drug Dealer (ID:28)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Drug Dealer (ID:29)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Drug Dealer (ID:30)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Farm-Town inhabitant (ID:31)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Farm-Town inhabitant (ID:32)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Farm-Town inhabitant (ID:33)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Farm-Town inhabitant (ID:34)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gardener (ID:35)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Golfer (ID:36)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Golfer (ID:37)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:38)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:39)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:40)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:41)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Jethro (ID:42)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:43)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:44)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Beach Visitor (ID:45)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:46)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:47)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:48)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Snakehead (Da Nang) (ID:49)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Mechanic (ID:50)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Mountain Biker (ID:51)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Mountain Biker (ID:52)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Unknown (ID:53)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:54)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:55)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:56)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Oriental Ped (ID:57)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Oriental Ped (ID:58)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:59)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:60)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Pilot (ID:61)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Colonel Fuhrberger (ID:62)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Prostitute (ID:63)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Prostitute (ID:64)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Kendl Johnson (ID:65)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Pool Player (ID:66)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Pool Player (ID:67)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Priest/Preacher (ID:68)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:69)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Scientist (ID:70)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Security Guard (ID:71)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Hippy (ID:72)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Hippy (ID:73)", color => '-1');
	$ItemInfo[] = array( name => "Скин: CJ (ID:74)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Prostitute (ID:75)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:76)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Homeless (ID:77)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Homeless (ID:78)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Homeless (ID:79)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Boxer (ID:80)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Boxer (ID:81)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Black Elvis (ID:82)", color => '-1');
	$ItemInfo[] = array( name => "Скин: White Elvis (ID:83)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Blue Elvis (ID:84)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Prostitute (ID:85)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Ryder with robbery mask (ID:86)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Stripper (ID:87)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:88)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:89)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Jogger (ID:90)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rich Woman (ID:91)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rollerskater (ID:92)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:93)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:94)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:95)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Jogger (ID:96)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Lifeguard (ID:97)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Normal Ped (ID:98)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rollerskater (ID:99)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Biker (ID:100)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:101)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:102)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:103)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:104)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:105)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:106)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:107)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:108)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:109)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:110)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:111)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:112)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:113)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:114)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:115)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:116)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:117)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:118)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:119)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:120)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:121)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:122)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:123)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:124)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:125)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:126)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:127)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:128)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:129)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:130)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:131)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:132)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:133)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:134)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:135)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:136)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:137)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:138)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:139)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:140)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:141)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:142)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:143)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:144)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:145)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:146)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:147)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:148)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:149)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:150)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:151)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:152)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:153)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:154)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:155)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:156)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:157)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:158)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:159)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:160)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:161)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:162)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:163)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:164)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:165)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:166)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:167)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:168)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:169)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:170)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:171)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:172)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:173)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:174)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:175)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:176)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:177)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:178)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:179)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:180)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:181)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:182)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:183)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:184)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:185)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:186)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:187)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:188)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:189)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:190)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:191)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:192)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:193)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:194)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:195)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:196)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:197)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:198)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:199)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:200)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:201)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:202)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:203)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:204)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:205)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:206)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:207)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:208)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:209)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:210)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:211)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:212)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:213)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:214)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:215)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:216)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:217)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:218)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:219)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:220)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:221)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:222)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:223)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:224)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:225)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:226)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:227)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:228)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:229)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Homeless (ID:230)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:231)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:232)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:233)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:234)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:235)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:236)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:237)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:238)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:239)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:240)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:241)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:242)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:243)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:244)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:245)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:246)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:247)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:248)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:249)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:250)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:251)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:252)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:253)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:254)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:255)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:256)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:257)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:258)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:259)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:260)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:261)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:262)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:263)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:264)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:265)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:266)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:267)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:268)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:269)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:270)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:271)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:272)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:273)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:274)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:275)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:276)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:277)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:278)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:279)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:280)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:281)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:282)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:283)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:284)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:285)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:286)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:287)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:288)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:289)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:290)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:291)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:292)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:293)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:294)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:295)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:296)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:297)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:298)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:299)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:300)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:301)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:302)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:303)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:304)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:305)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:306)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:307)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:308)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:309)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:310)", color => '-1');
	$ItemInfo[] = array( name => "Скин: (ID:311)", color => '-1');
	$ItemInfo[] = array( name => "Скин: ID(:)", color => '-1');
	$ItemInfo[] = array( name => "Сундук рулетки", color => '-1');
	$ItemInfo[] = array( name => "Аптечка", color => '-1');
	$ItemInfo[] = array( name => "Чипсы", color => '-1');
	$ItemInfo[] = array( name => "Фишки для казино", color => '-1');
	$ItemInfo[] = array( name => "Яд", color => '-1');
	$ItemInfo[] = array( name => "Набор для починки", color => '-1');
	$ItemInfo[] = array( name => "Маска", color => '-1');
	$ItemInfo[] = array( name => "Зажигалка", color => '-1');
	$ItemInfo[] = array( name => "Сигарета", color => '-1');
	$ItemInfo[] = array( name => "Золотая рулетка", color => '-1');
	$ItemInfo[] = array( name => "Серебряная рулетка", color => '-1');
	$ItemInfo[] = array( name => "Бронзовая рулетка", color => '-1');
	$ItemInfo[] = array( name => "Пиво", color => '-1');
	$ItemInfo[] = array( name => "Спранк", color => '-1');
	$ItemInfo[] = array( name => "Телефонная книга", color => '-1');
	$ItemInfo[] = array( name => "Скрепка", color => '-1');
	$ItemInfo[] = array( name => "Телефон Xiaomi Mi 8 (Белый)", color => '-1');
	$ItemInfo[] = array( name => "Бронежилет", color => '-1');
	$ItemInfo[] = array( name => "Баллончик с краской", color => '-1');
	$ItemInfo[] = array( name => "Канистра", color => '-1');
	$ItemInfo[] = array( name => "Наклейка Supreme", color => '-1');
	$ItemInfo[] = array( name => "Колонка", color => '-1');
	$ItemInfo[] = array( name => "Подарок", color => '-1');
	$ItemInfo[] = array( name => "Огнетушитель", color => '-1');
	$ItemInfo[] = array( name => "Бита с гвоздями", color => '-1');
	$ItemInfo[] = array( name => "Меч", color => '-1');
	$ItemInfo[] = array( name => "Кирка", color => '-1');
	$ItemInfo[] = array( name => "Маска CJ", color => '-1');
	$ItemInfo[] = array( name => "Красный чемодан", color => '-1');
	$ItemInfo[] = array( name => "Шлем", color => '-1');
	$ItemInfo[] = array( name => "Белая маска", color => '-1');
	$ItemInfo[] = array( name => "Красная маска", color => '-1');
	$ItemInfo[] = array( name => "Зеленая маска", color => '-1');
	$ItemInfo[] = array( name => "Мусор", color => '-1');
	$ItemInfo[] = array( name => "Ресурс: Хлопок", color => '-1');
	$ItemInfo[] = array( name => "Бумбокс", color => '-1');
	$ItemInfo[] = array( name => "Синяя шапка", color => '-1');
	$ItemInfo[] = array( name => "Красная шапка", color => '-1');
	$ItemInfo[] = array( name => "Зеленая шапка", color => '-1');
	$ItemInfo[] = array( name => "Жилет", color => '-1');
	$ItemInfo[] = array( name => "Повязка на шею", color => '-1');
	$ItemInfo[] = array( name => "Клюшка", color => '-1');
	$ItemInfo[] = array( name => "Бита", color => '-1');
	$ItemInfo[] = array( name => "Лопата", color => '-1');
	$ItemInfo[] = array( name => "Кий", color => '-1');
	$ItemInfo[] = array( name => "Катана", color => '-1');
	$ItemInfo[] = array( name => "Трость", color => '-1');
	$ItemInfo[] = array( name => "Полицейская кепка", color => '-1');
	$ItemInfo[] = array( name => "Щит", color => '-1');
	$ItemInfo[] = array( name => "Ресурс: Камень", color => '-1');
	$ItemInfo[] = array( name => "Ресурс: Золото", color => '-1');
	$ItemInfo[] = array( name => "Ресурс: Серебро", color => '-1');
	$ItemInfo[] = array( name => "Семейный талон", color => '-1');
	$ItemInfo[] = array( name => "Таблетка адреналина", color => '-1');
	$ItemInfo[] = array( name => "Хуй", color => '-1');
	$ItemInfo[] = array( name => "Сертификат FBI Truck", color => '-1');
	$ItemInfo[] = array( name => "Карнавальный веер", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Vortex", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Raindance", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Cement Truck", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Infernus (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Cheetah (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Buffalo (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Banshee (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Bullet (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Comet (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Super GT (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Huntley (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Turismo (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Белый)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Голубой)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Зеленый)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Оранжевый)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Золотой)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Розовый)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Черный)", color => '-1');
	$ItemInfo[] = array( name => "Телефон Google Pixel 3 (Желтый)", color => '-1');
	$ItemInfo[] = array( name => "Цилиндр (Белый)", color => '-1');
	$ItemInfo[] = array( name => "Цилиндр (Черный)", color => '-1');
	$ItemInfo[] = array( name => "Усы", color => '-1');
	$ItemInfo[] = array( name => "Белая гитара", color => '-1');
	$ItemInfo[] = array( name => "Черная гитара", color => '-1');
	$ItemInfo[] = array( name => "Красная гитара", color => '-1');
	$ItemInfo[] = array( name => "Респиратор", color => '-1');
	$ItemInfo[] = array( name => "Амулет", color => '-1');
	$ItemInfo[] = array( name => "Новогодняя шапка", color => '-1');
	$ItemInfo[] = array( name => "Новогодняя шапка", color => '-1');
	$ItemInfo[] = array( name => "Новогодняя шапка", color => '-1');
	$ItemInfo[] = array( name => "Подарок (Аксессуар)", color => '-1');
	$ItemInfo[] = array( name => "Подарок (Аксессуар)", color => '-1');
	$ItemInfo[] = array( name => "Подарок (Аксессуар)", color => '-1');
	$ItemInfo[] = array( name => "Подарок (Аксессуар)", color => '-1');
	$ItemInfo[] = array( name => "Подарок (Аксессуар)", color => '-1');
	$ItemInfo[] = array( name => "Повязка на глаз", color => '-1');
	$ItemInfo[] = array( name => "Тушка оленя", color => '-1');
	$ItemInfo[] = array( name => "Голова дьявола", color => '-1');
	$ItemInfo[] = array( name => "Маска петуха", color => '-1');
	$ItemInfo[] = array( name => "Хотдог", color => '-1');
	$ItemInfo[] = array( name => "Маска кентавра", color => '-1');
	$ItemInfo[] = array( name => "Боксерский шлем", color => '-1');
	$ItemInfo[] = array( name => "Мясо на спину", color => '-1');
	$ItemInfo[] = array( name => "Дреды", color => '-1');
	$ItemInfo[] = array( name => "Сумка для ноутбука", color => '-1');
	$ItemInfo[] = array( name => "Бургер на голову", color => '-1');
	$ItemInfo[] = array( name => "Шлем SWAT", color => '-1');
	$ItemInfo[] = array( name => "Рога на голову", color => '-1');
	$ItemInfo[] = array( name => "Маска зомби", color => '-1');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-1');
	$ItemInfo[] = array( name => "Скейт", color => '-1');
	$ItemInfo[] = array( name => "Телефон Samsung Galaxy S10 (Белый)", color => '-1');
	$ItemInfo[] = array( name => "Доска для серфинга", color => '-1');
	$ItemInfo[] = array( name => "Переносной ларек (2)", color => '-1');
	$ItemInfo[] = array( name => "Наушники", color => '-1');
	$ItemInfo[] = array( name => "Наушники", color => '-1');
	$ItemInfo[] = array( name => "Наушники", color => '-1');
	$ItemInfo[] = array( name => "Наушники", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Шапка", color => '-1');
	$ItemInfo[] = array( name => "Панамка", color => '-1');
	$ItemInfo[] = array( name => "Панамка", color => '-1');
	$ItemInfo[] = array( name => "Панамка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Кепка", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Каска", color => '-1');
	$ItemInfo[] = array( name => "Берет", color => '-1');
	$ItemInfo[] = array( name => "Берет", color => '-1');
	$ItemInfo[] = array( name => "Берет", color => '-1');
	$ItemInfo[] = array( name => "Берет", color => '-1');
	$ItemInfo[] = array( name => "Берет", color => '-1');
	$ItemInfo[] = array( name => "Парик", color => '-1');
	$ItemInfo[] = array( name => "Парик", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Очки", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Бандана", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Часы", color => '-1');
	$ItemInfo[] = array( name => "Портфель", color => '-1');
	$ItemInfo[] = array( name => "Портфель", color => '-1');
	$ItemInfo[] = array( name => "Портфель", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа", color => '-1');
	$ItemInfo[] = array( name => "Бандана на голову", color => '-1');
	$ItemInfo[] = array( name => "Бандана на голову", color => '-1');
	$ItemInfo[] = array( name => "Бандана на голову", color => '-1');
	$ItemInfo[] = array( name => "Бандана на голову", color => '-1');
	$ItemInfo[] = array( name => "Бандана на голову", color => '-1');
	$ItemInfo[] = array( name => "Радио", color => '-1');
	$ItemInfo[] = array( name => "Удочка", color => '-1');
	$ItemInfo[] = array( name => "Черви", color => '-1');
	$ItemInfo[] = array( name => "Таблетки от наркозависимости", color => '-1');
	$ItemInfo[] = array( name => "Наркотики", color => '-1');
	$ItemInfo[] = array( name => "Кастет", color => '-1');
	$ItemInfo[] = array( name => "Бита", color => '-1');
	$ItemInfo[] = array( name => "Катана", color => '-1');
	$ItemInfo[] = array( name => "Парашют", color => '-1');
	$ItemInfo[] = array( name => "Газовая шашка", color => '-1');
	$ItemInfo[] = array( name => "Desert Eagle", color => '-1');
	$ItemInfo[] = array( name => "Shotgun", color => '-1');
	$ItemInfo[] = array( name => "MP5", color => '-1');
	$ItemInfo[] = array( name => "Автомат Калашникова", color => '-1');
	$ItemInfo[] = array( name => "M4", color => '-1');
	$ItemInfo[] = array( name => "Country Rifle", color => '-1');
	$ItemInfo[] = array( name => "Очки ночного видения", color => '-1');
	$ItemInfo[] = array( name => "Талон: +1 AZ Coins", color => '-1');
	$ItemInfo[] = array( name => "Бронза", color => '-1');
	$ItemInfo[] = array( name => "Метал", color => '-1');
	$ItemInfo[] = array( name => "Попугай на плечо", color => '-1');
	$ItemInfo[] = array( name => "Крылья на спину", color => '-1');
	$ItemInfo[] = array( name => "Самолетик", color => '-1');
	$ItemInfo[] = array( name => "Крест", color => '-1');
	$ItemInfo[] = array( name => "Фуражка полицейского", color => '-1');
	$ItemInfo[] = array( name => "Летняя монета", color => '-1');
	$ItemInfo[] = array( name => "Калаш в жопу", color => '-1');
	$ItemInfo[] = array( name => "Наклейка Launch", color => '-1');
	$ItemInfo[] = array( name => "Жареная рыба", color => '-1');
	$ItemInfo[] = array( name => "Реферальная монета", color => '-1');
	$ItemInfo[] = array( name => "Телефон Iphone X (Серебряный)", color => '-1');
	$ItemInfo[] = array( name => "Дрова", color => '-1');
	$ItemInfo[] = array( name => "Материалы", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Windsor (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Jester (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Sultan (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Elegy (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Phoenix (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Cabbie (Лаунч)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Maverick", color => '-1');
	$ItemInfo[] = array( name => "Сертификат NRG-500", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Karting", color => '-1');
	$ItemInfo[] = array( name => "San News Maverick", color => '-1');
	$ItemInfo[] = array( name => "Police Rancher", color => '-1');
	$ItemInfo[] = array( name => "Police Maverick", color => '-1');
	$ItemInfo[] = array( name => "Mountain Bike", color => '-1');
	$ItemInfo[] = array( name => "Shamal", color => '-1');
	$ItemInfo[] = array( name => "Police Motocycle", color => '-1');
	$ItemInfo[] = array( name => "FBI Truck", color => '-1');
	$ItemInfo[] = array( name => "Monster Truck A", color => '-1');
	$ItemInfo[] = array( name => "Monster Truck B", color => '-1');
	$ItemInfo[] = array( name => "Carting Car", color => '-1');
	$ItemInfo[] = array( name => "LSPD Car", color => '-1');
	$ItemInfo[] = array( name => "SFPD Car", color => '-1');
	$ItemInfo[] = array( name => "LVPD Car", color => '-1');
	$ItemInfo[] = array( name => "RCPD Rancher", color => '-1');
	$ItemInfo[] = array( name => "Dune", color => '-1');
	$ItemInfo[] = array( name => "Твин-турбо", color => '-1');
	$ItemInfo[] = array( name => "Sport-Infernus", color => '-1');
	$ItemInfo[] = array( name => "Sport-Bullet", color => '-1');
	$ItemInfo[] = array( name => "Sport-Cheetah", color => '-1');
	$ItemInfo[] = array( name => "Дом", color => '-1');
	$ItemInfo[] = array( name => "Золото на спину", color => '-1');
	$ItemInfo[] = array( name => "Вибратор на спину #1", color => '-1');
	$ItemInfo[] = array( name => "Бомба на спину", color => '-1');
	$ItemInfo[] = array( name => "Бензопила", color => '-1');
	$ItemInfo[] = array( name => "Halloween Tuning", color => '-1');
	$ItemInfo[] = array( name => "ModificationC", color => '-1');
	$ItemInfo[] = array( name => "Новогодний мешок", color => '-1');
	$ItemInfo[] = array( name => "Эффект x4 пополнение счёта)", color => '-1');
	$ItemInfo[] = array( name => "Талон EXP", color => '-1');
	$ItemInfo[] = array( name => "Деньги", color => '-1');
	$ItemInfo[] = array( name => "Доллар", color => '-1');
	$ItemInfo[] = array( name => "Бомба", color => '-1');
	$ItemInfo[] = array( name => "Рюкзак", color => '-1');
	$ItemInfo[] = array( name => "Коса на спину", color => '-1');
	$ItemInfo[] = array( name => "Флаг на спину", color => '-1');
	$ItemInfo[] = array( name => "Миниган", color => '-1');
	$ItemInfo[] = array( name => "Бутылка на спину", color => '-1');
	$ItemInfo[] = array( name => "Пулемет", color => '-1');
	$ItemInfo[] = array( name => "Огнемет", color => '-1');
	$ItemInfo[] = array( name => "Сердце на грудь", color => '-1');
	$ItemInfo[] = array( name => "Ресурс: Лён", color => '-1');
	$ItemInfo[] = array( name => "Грабли", color => '-1');
	$ItemInfo[] = array( name => "Чемодан ( Коричневый )", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #1", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #2", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #3", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #4", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #5", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #6", color => '-1');
	$ItemInfo[] = array( name => "Воздушный шар #7", color => '-1');
	$ItemInfo[] = array( name => "Фотоаппарат на грудь", color => '-1');
	$ItemInfo[] = array( name => "Молоток на спину", color => '-1');
	$ItemInfo[] = array( name => "Евро", color => '-1');
	$ItemInfo[] = array( name => "Антибиотик", color => '-1');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-1');
	$ItemInfo[] = array( name => "Ангельское кольцо на голову", color => '-1');
	$ItemInfo[] = array( name => "Шляпа ведьмы", color => '-1');
	$ItemInfo[] = array( name => "Бита", color => '-55040');
	$ItemInfo[] = array( name => "Бита", color => '-7575279');
	$ItemInfo[] = array( name => "Бита", color => '-23040');
	$ItemInfo[] = array( name => "Бита", color => '-1322933');
	$ItemInfo[] = array( name => "Бита", color => '-16711681');
	$ItemInfo[] = array( name => "Бита", color => '-13256638');
	$ItemInfo[] = array( name => "Бита", color => '-13484548');
	$ItemInfo[] = array( name => "Бита", color => '-2468875');
	$ItemInfo[] = array( name => "Бита", color => '-3057548');
	$ItemInfo[] = array( name => "Щит", color => '-3398618');
	$ItemInfo[] = array( name => "Щит", color => '-3377116');
	$ItemInfo[] = array( name => "Щит", color => '-1655778');
	$ItemInfo[] = array( name => "Щит", color => '-2762948');
	$ItemInfo[] = array( name => "Щит", color => '-12789952');
	$ItemInfo[] = array( name => "Щит", color => '-12789801');
	$ItemInfo[] = array( name => "Щит", color => '-12828969');
	$ItemInfo[] = array( name => "Щит", color => '-2671404');
	$ItemInfo[] = array( name => "Щит", color => '-2671490');
	$ItemInfo[] = array( name => "Катана", color => '-3398618');
	$ItemInfo[] = array( name => "Катана", color => '-3377116');
	$ItemInfo[] = array( name => "Катана", color => '-1655778');
	$ItemInfo[] = array( name => "Катана", color => '-2762948');
	$ItemInfo[] = array( name => "Катана", color => '-12789952');
	$ItemInfo[] = array( name => "Катана", color => '-12789801');
	$ItemInfo[] = array( name => "Катана", color => '-12828969');
	$ItemInfo[] = array( name => "Катана", color => '-2671404');
	$ItemInfo[] = array( name => "Катана", color => '-2671490');
	$ItemInfo[] = array( name => "Маска CJ", color => '-3398618');
	$ItemInfo[] = array( name => "Маска CJ", color => '-3377116');
	$ItemInfo[] = array( name => "Маска CJ", color => '-1655778');
	$ItemInfo[] = array( name => "Маска CJ", color => '-2762948');
	$ItemInfo[] = array( name => "Маска CJ", color => '-12789952');
	$ItemInfo[] = array( name => "Маска CJ", color => '-12789801');
	$ItemInfo[] = array( name => "Маска CJ", color => '-12828969');
	$ItemInfo[] = array( name => "Маска CJ", color => '-2671404');
	$ItemInfo[] = array( name => "Маска CJ", color => '-2671490');
	$ItemInfo[] = array( name => "Меч", color => '-3398618');
	$ItemInfo[] = array( name => "Меч", color => '-3377116');
	$ItemInfo[] = array( name => "Меч", color => '-1655778');
	$ItemInfo[] = array( name => "Меч", color => '-2762948');
	$ItemInfo[] = array( name => "Меч", color => '-12789952');
	$ItemInfo[] = array( name => "Меч", color => '-12789801');
	$ItemInfo[] = array( name => "Меч", color => '-12828969');
	$ItemInfo[] = array( name => "Меч", color => '-2671404');
	$ItemInfo[] = array( name => "Меч", color => '-2671490');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-3398618');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-3377116');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-1655778');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-2762948');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-12789952');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-12789801');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-12828969');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-2671404');
	$ItemInfo[] = array( name => "Маска от короновируса", color => '-2671490');
	$ItemInfo[] = array( name => "Белая маска", color => '-3398618');
	$ItemInfo[] = array( name => "Белая маска", color => '-3377116');
	$ItemInfo[] = array( name => "Белая маска", color => '-1655778');
	$ItemInfo[] = array( name => "Белая маска", color => '-2762948');
	$ItemInfo[] = array( name => "Белая маска", color => '-12789952');
	$ItemInfo[] = array( name => "Белая маска", color => '-12789801');
	$ItemInfo[] = array( name => "Белая маска", color => '-12828969');
	$ItemInfo[] = array( name => "Белая маска", color => '-2671404');
	$ItemInfo[] = array( name => "Белая маска", color => '-2671490');
	$ItemInfo[] = array( name => "Сундук рулетки (донат)", color => '-1');
	$ItemInfo[] = array( name => "Переносной ларек (1)", color => '-1');
	$ItemInfo[] = array( name => "Переносной ларек (3)", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер", color => '-1');
	$ItemInfo[] = array( name => "Рога", color => '-1');
	$ItemInfo[] = array( name => "Черепаха на авто", color => '-1');
	$ItemInfo[] = array( name => "Неон (Красный)", color => '-1');
	$ItemInfo[] = array( name => "Неон (Синий)", color => '-1');
	$ItemInfo[] = array( name => "Неон (Зелёный)", color => '-1');
	$ItemInfo[] = array( name => "Неон (Жёлтый)", color => '-1');
	$ItemInfo[] = array( name => "Неон (Фиолетовый)", color => '-1');
	$ItemInfo[] = array( name => "Неон (Белый)", color => '-1');
	$ItemInfo[] = array( name => "Звезда на авто", color => '-1');
	$ItemInfo[] = array( name => "Логотип ФБР", color => '-1');
	$ItemInfo[] = array( name => "Амулет на авто", color => '-1');
	$ItemInfo[] = array( name => "Мигалка на авто", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (Жёлтая)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (Чёрная)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (Белая)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (Чёрная)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Maverick (ПРЕМИУМ)", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер (Emerald)", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер (Красный шёлк)", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер (Дорожная служба)", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер (Красный)", color => '-1');
	$ItemInfo[] = array( name => "Цветы", color => '-1');
	$ItemInfo[] = array( name => "Сим карта", color => '-1');
	$ItemInfo[] = array( name => "Фотоаппарат", color => '-1');
	$ItemInfo[] = array( name => "Бензопила", color => '-1');
	$ItemInfo[] = array( name => "Отмычка", color => '-1');
	$ItemInfo[] = array( name => "Замок для велосипеда", color => '-1');
	$ItemInfo[] = array( name => "Картофель-фри", color => '-1');
	$ItemInfo[] = array( name => "Сэндвич", color => '-1');
	$ItemInfo[] = array( name => "Бургер", color => '-1');
	$ItemInfo[] = array( name => "Крылышки", color => '-1');
	$ItemInfo[] = array( name => "Пицца", color => '-1');
	$ItemInfo[] = array( name => "Курица с салатом", color => '-1');
	$ItemInfo[] = array( name => "Комплексный обед", color => '-1');
	$ItemInfo[] = array( name => "Виски", color => '-1');
	$ItemInfo[] = array( name => "Коньяк", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Спойлер", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Боковая юбка", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Турбина", color => '-1');
	$ItemInfo[] = array( name => "Фара", color => '-1');
	$ItemInfo[] = array( name => "Фара", color => '-1');
	$ItemInfo[] = array( name => "Нитро x1", color => '-1');
	$ItemInfo[] = array( name => "Нитро x5", color => '-1');
	$ItemInfo[] = array( name => "Нитро x10", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Воздухозаброник", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Задний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Передний бампер", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка", color => '-1');
	$ItemInfo[] = array( name => "Наклейка на бампер", color => '-1');
	$ItemInfo[] = array( name => "Неон - Красный", color => '-1');
	$ItemInfo[] = array( name => "Неон - Синий", color => '-1');
	$ItemInfo[] = array( name => "Неон - Зеленый", color => '-1');
	$ItemInfo[] = array( name => "Неон - Желтый", color => '-1');
	$ItemInfo[] = array( name => "Неон - Розовый", color => '-1');
	$ItemInfo[] = array( name => "Неон - Белый", color => '-1');
	$ItemInfo[] = array( name => "Чемодан", color => '-1');
	$ItemInfo[] = array( name => "Мина", color => '-1');
	$ItemInfo[] = array( name => "Сердце", color => '-1');
	$ItemInfo[] = array( name => "Звезда", color => '-1');
	$ItemInfo[] = array( name => "Иконка съёмки", color => '-1');
	$ItemInfo[] = array( name => "Иконка дома", color => '-1');
	$ItemInfo[] = array( name => "Иконка дома", color => '-1');
	$ItemInfo[] = array( name => "Доллар", color => '-1');
	$ItemInfo[] = array( name => "Одежда", color => '-1');
	$ItemInfo[] = array( name => "Амулет", color => '-1');
	$ItemInfo[] = array( name => "Дискета", color => '-1');
	$ItemInfo[] = array( name => "Два черепа", color => '-1');
	$ItemInfo[] = array( name => "Два человека", color => '-1');
	$ItemInfo[] = array( name => "Стрелка", color => '-1');
	$ItemInfo[] = array( name => "Пицца", color => '-1');
	$ItemInfo[] = array( name => "Человек", color => '-1');
	$ItemInfo[] = array( name => "Девушка с пистолетом", color => '-1');
	$ItemInfo[] = array( name => "Девушка", color => '-1');
	$ItemInfo[] = array( name => "Шипы", color => '-1');
	$ItemInfo[] = array( name => "Черепаха", color => '-1');
	$ItemInfo[] = array( name => "Канистра", color => '-1');
	$ItemInfo[] = array( name => "Бомба", color => '-1');
	$ItemInfo[] = array( name => "Олень с рогами", color => '-1');
	$ItemInfo[] = array( name => "Игральный кубик", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Одна фишка", color => '-1');
	$ItemInfo[] = array( name => "Доска для сёрфинга", color => '-1');
	$ItemInfo[] = array( name => "Доска для сёрфинга", color => '-1');
	$ItemInfo[] = array( name => "Доска для сёрфинга", color => '-1');
	$ItemInfo[] = array( name => "Самолётик", color => '-1');
	$ItemInfo[] = array( name => "Большой Самолётик", color => '-1');
	$ItemInfo[] = array( name => "Огнетушитель", color => '-1');
	$ItemInfo[] = array( name => "Кальян", color => '-1');
	$ItemInfo[] = array( name => "Голова зомби", color => '-1');
	$ItemInfo[] = array( name => "Флаг (зеленый)", color => '-1');
	$ItemInfo[] = array( name => "Флаг (т. зеленый)", color => '-1');
	$ItemInfo[] = array( name => "Голова полицейского", color => '-1');
	$ItemInfo[] = array( name => "Ящик с патронами", color => '-1');
	$ItemInfo[] = array( name => "Катана", color => '-1');
	$ItemInfo[] = array( name => "Магнит", color => '-1');
	$ItemInfo[] = array( name => "Амулет", color => '-1');
	$ItemInfo[] = array( name => "Стрелка (белая)", color => '-1');
	$ItemInfo[] = array( name => "Круглая стрелка (синяя)", color => '-1');
	$ItemInfo[] = array( name => "Подкова", color => '-1');
	$ItemInfo[] = array( name => "Иконка патронов", color => '-1');
	$ItemInfo[] = array( name => "Набор аптечки", color => '-1');
	$ItemInfo[] = array( name => "Логотип FBI", color => '-1');
	$ItemInfo[] = array( name => "Полицейская мигалка", color => '-1');
	$ItemInfo[] = array( name => "Копченая ножка", color => '-1');
	$ItemInfo[] = array( name => "Балон", color => '-1');
	$ItemInfo[] = array( name => "Меч", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (желтая)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (черный-1)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (белый)", color => '-1');
	$ItemInfo[] = array( name => "Шашка такси (черный-2)", color => '-1');
	$ItemInfo[] = array( name => "Олень", color => '-1');
	$ItemInfo[] = array( name => "Темная гитара", color => '-1');
	$ItemInfo[] = array( name => "Черно-белая гитара", color => '-1');
	$ItemInfo[] = array( name => "Черная гитара", color => '-1');
	$ItemInfo[] = array( name => "Бургер", color => '-1');
	$ItemInfo[] = array( name => "Молот", color => '-1');
	$ItemInfo[] = array( name => "Скейт", color => '-1');
	$ItemInfo[] = array( name => "Голова дьявола", color => '-1');
	$ItemInfo[] = array( name => "Церковный крест", color => '-1');
	$ItemInfo[] = array( name => "Новог. игрушка (синяя)", color => '-1');
	$ItemInfo[] = array( name => "Новог. игрушка (красная)", color => '-1');
	$ItemInfo[] = array( name => "Новог. игрушка (зеленая)", color => '-1');
	$ItemInfo[] = array( name => "Новог. игрушка (желтая)", color => '-1');
	$ItemInfo[] = array( name => "Новог. игрушка (серая)", color => '-1');
	$ItemInfo[] = array( name => "Попугай", color => '-1');
	$ItemInfo[] = array( name => "Рога", color => '-1');
	$ItemInfo[] = array( name => "Тыква", color => '-1');
	$ItemInfo[] = array( name => "Снегоуборочный бампер", color => '-1');
	$ItemInfo[] = array( name => "Подиум", color => '-1');
	$ItemInfo[] = array( name => "Бита", color => '-1');
	$ItemInfo[] = array( name => "Электродвигатель", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 1", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 2", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 3", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 4", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 5", color => '-1');
	$ItemInfo[] = array( name => "Магнитола - 6", color => '-1');
	$ItemInfo[] = array( name => "Серая колонка", color => '-1');
	$ItemInfo[] = array( name => "Саб", color => '-1');
	$ItemInfo[] = array( name => "Деревянная колонка", color => '-1');
	$ItemInfo[] = array( name => "Большая колонка", color => '-1');
	$ItemInfo[] = array( name => "Премиум (Maverick)", color => '-1');
	$ItemInfo[] = array( name => "Скидочный талон", color => '-1');
	$ItemInfo[] = array( name => "Танк на радиоуправлении", color => '-1');
	$ItemInfo[] = array( name => "Машинка на радиоуправлении", color => '-1');
	$ItemInfo[] = array( name => "Самолёт на радиоуправлении", color => '-1');
	$ItemInfo[] = array( name => "Вертолёт на радиоуправлении (1)", color => '-1');
	$ItemInfo[] = array( name => "Вертолёт на радиоуправлении (2)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Дарт-вейдер (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Смерть (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Сет дракона (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Сет демона (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Соник (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Спарта (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Пабг (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Байкер (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Нигер (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Ангел (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Военный Билет", color => '-1');
	$ItemInfo[] = array( name => "Щит", color => '-1');
	$ItemInfo[] = array( name => "Крылья Устрицы", color => '-1');
	$ItemInfo[] = array( name => "Шапка Оленя", color => '-1');
	$ItemInfo[] = array( name => "Лейка", color => '-1');
	$ItemInfo[] = array( name => "Улучшение для автомобиля", color => '-1');
	$ItemInfo[] = array( name => "Курица на плечо", color => '-1');
	$ItemInfo[] = array( name => "Классик", color => '-1');
	$ItemInfo[] = array( name => "Футуристик", color => '-1');
	$ItemInfo[] = array( name => "Киберпанк", color => '-1');
	$ItemInfo[] = array( name => "Future Taxi", color => '-1');
	$ItemInfo[] = array( name => "Модификация Праздник (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Экза", color => '-1');
	$ItemInfo[] = array( name => "Спанч Боб (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Меч зеленый", color => '-1');
	$ItemInfo[] = array( name => "Меч желтый", color => '-1');
	$ItemInfo[] = array( name => "Меч фиолетовый", color => '-1');
	$ItemInfo[] = array( name => "Меч розовый", color => '-1');
	$ItemInfo[] = array( name => "Меч голубой", color => '-1');
	$ItemInfo[] = array( name => "Меч оранжевый", color => '-1');
	$ItemInfo[] = array( name => "Кресло качалка", color => '-1');
	$ItemInfo[] = array( name => "Светильник белый", color => '-1');
	$ItemInfo[] = array( name => "Светильник синий", color => '-1');
	$ItemInfo[] = array( name => "Светильник зеленый", color => '-1');
	$ItemInfo[] = array( name => "Светильник красный", color => '-1');
	$ItemInfo[] = array( name => "Светильник желтый", color => '-1');
	$ItemInfo[] = array( name => "Светильник голубой", color => '-1');
	$ItemInfo[] = array( name => "Светильник фиолетовый", color => '-1');
	$ItemInfo[] = array( name => "Костер", color => '-1');
	$ItemInfo[] = array( name => "Красный мангал", color => '-1');
	$ItemInfo[] = array( name => "Серый мангал", color => '-1');
	$ItemInfo[] = array( name => "Металический стул", color => '-1');
	$ItemInfo[] = array( name => "Красный стул", color => '-1');
	$ItemInfo[] = array( name => "Деревянный стол", color => '-1');
	$ItemInfo[] = array( name => "Лавка", color => '-1');
	$ItemInfo[] = array( name => "Металический стол", color => '-1');
	$ItemInfo[] = array( name => "Мяч", color => '-1');
	$ItemInfo[] = array( name => "Диван", color => '-1');
	$ItemInfo[] = array( name => "Цветок в сером горшке", color => '-1');
	$ItemInfo[] = array( name => "Красный цветок в горшке", color => '-1');
	$ItemInfo[] = array( name => "Кактус", color => '-1');
	$ItemInfo[] = array( name => "Куст 1", color => '-1');
	$ItemInfo[] = array( name => "Цветы", color => '-1');
	$ItemInfo[] = array( name => "Дерево 1", color => '-1');
	$ItemInfo[] = array( name => "Дерево 2", color => '-1');
	$ItemInfo[] = array( name => "Дерево 3", color => '-1');
	$ItemInfo[] = array( name => "Большой куст 1", color => '-1');
	$ItemInfo[] = array( name => "Большой куст 2", color => '-1');
	$ItemInfo[] = array( name => "Папоротник", color => '-1');
	$ItemInfo[] = array( name => "Пляжный куст", color => '-1');
	$ItemInfo[] = array( name => "Зеленый лежак", color => '-1');
	$ItemInfo[] = array( name => "Серый лежак", color => '-1');
	$ItemInfo[] = array( name => "Стул и стол 1", color => '-1');
	$ItemInfo[] = array( name => "Тент", color => '-1');
	$ItemInfo[] = array( name => "Стул и стол 2", color => '-1');
	$ItemInfo[] = array( name => "Лавка", color => '-1');
	$ItemInfo[] = array( name => "Стул и стол 3", color => '-1');
	$ItemInfo[] = array( name => "Бутылка с вином", color => '-1');
	$ItemInfo[] = array( name => "Стул и стол 4", color => '-1');
	$ItemInfo[] = array( name => "Красный стол", color => '-1');
	$ItemInfo[] = array( name => "Красный стол в клетку", color => '-1');
	$ItemInfo[] = array( name => "Черный стул", color => '-1');
	$ItemInfo[] = array( name => "Красный стул в клетку", color => '-1');
	$ItemInfo[] = array( name => "Два стула и стол", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 1", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 2", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 3", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 4", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 5", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 6", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 7", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 8", color => '-1');
	$ItemInfo[] = array( name => "Растение в горшке 1", color => '-1');
	$ItemInfo[] = array( name => "Растение в горшке 2", color => '-1');
	$ItemInfo[] = array( name => "Растение в горшке 3", color => '-1');
	$ItemInfo[] = array( name => "Растение в горшке 4", color => '-1');
	$ItemInfo[] = array( name => "Растение в форме лавки", color => '-1');
	$ItemInfo[] = array( name => "Белая ваза", color => '-1');
	$ItemInfo[] = array( name => "Серая ваза", color => '-1');
	$ItemInfo[] = array( name => "Цветок в горшке 9", color => '-1');
	$ItemInfo[] = array( name => "Настенный цветок 1", color => '-1');
	$ItemInfo[] = array( name => "Настенный цветок 2", color => '-1');
	$ItemInfo[] = array( name => "Деревянный стул", color => '-1');
	$ItemInfo[] = array( name => "Коробки пиццы", color => '-1');
	$ItemInfo[] = array( name => "Пицца", color => '-1');
	$ItemInfo[] = array( name => "Коробки еды", color => '-1');
	$ItemInfo[] = array( name => "Чемодан", color => '-1');
	$ItemInfo[] = array( name => "Пачка денег", color => '-1');
	$ItemInfo[] = array( name => "Мешок денег", color => '-1');
	$ItemInfo[] = array( name => "Сейф денег", color => '-1');
	$ItemInfo[] = array( name => "Пакет наркотиков 1", color => '-1');
	$ItemInfo[] = array( name => "Пакет наркотиков 2", color => '-1');
	$ItemInfo[] = array( name => "M4 объект", color => '-1');
	$ItemInfo[] = array( name => "Винтовка объект", color => '-1');
	$ItemInfo[] = array( name => "Револьвер объект", color => '-1');
	$ItemInfo[] = array( name => "Дигл объект", color => '-1');
	$ItemInfo[] = array( name => "Дробовик 1", color => '-1');
	$ItemInfo[] = array( name => "Дробовик 2", color => '-1');
	$ItemInfo[] = array( name => "Дробовик 3", color => '-1');
	$ItemInfo[] = array( name => "AK47 объект", color => '-1');
	$ItemInfo[] = array( name => "MP5 объект", color => '-1');
	$ItemInfo[] = array( name => "Мусор 1", color => '-1');
	$ItemInfo[] = array( name => "Инвалидная коляска", color => '-1');
	$ItemInfo[] = array( name => "Коробки", color => '-1');
	$ItemInfo[] = array( name => "Мусор 2", color => '-1');
	$ItemInfo[] = array( name => "Мусор 3", color => '-1');
	$ItemInfo[] = array( name => "Пакет мусора", color => '-1');
	$ItemInfo[] = array( name => "Стальная мусорка", color => '-1');
	$ItemInfo[] = array( name => "Прозрачная мусорка", color => '-1');
	$ItemInfo[] = array( name => "Пластиковая мусорка", color => '-1');
	$ItemInfo[] = array( name => "Серая мусорка", color => '-1');
	$ItemInfo[] = array( name => "Большая зеленая мусорка с 5 коробками", color => '-1');
	$ItemInfo[] = array( name => "Большая зеленая мусорка", color => '-1');
	$ItemInfo[] = array( name => "Большая красная мусорка", color => '-1');
	$ItemInfo[] = array( name => "Большая синяя мусорка", color => '-1');
	$ItemInfo[] = array( name => "Деревянный забор 1", color => '-1');
	$ItemInfo[] = array( name => "Синий забор", color => '-1');
	$ItemInfo[] = array( name => "Забор из досок", color => '-1');
	$ItemInfo[] = array( name => "Деревянный забор 2", color => '-1');
	$ItemInfo[] = array( name => "Высокий забор", color => '-1');
	$ItemInfo[] = array( name => "Металлический забор", color => '-1');
	$ItemInfo[] = array( name => "Ограждение", color => '-1');
	$ItemInfo[] = array( name => "Стекляный забор", color => '-1');
	$ItemInfo[] = array( name => "Забор из сетки 1", color => '-1');
	$ItemInfo[] = array( name => "Забор из сетки 2", color => '-1');
	$ItemInfo[] = array( name => "Ноутбук", color => '-1');
	$ItemInfo[] = array( name => "Бутылка алкоголя 1", color => '-1');
	$ItemInfo[] = array( name => "Бутылка алкоголя 2", color => '-1');
	$ItemInfo[] = array( name => "Серая колонка", color => '-1');
	$ItemInfo[] = array( name => "Магнитофон", color => '-1');
	$ItemInfo[] = array( name => "Белый домофон", color => '-1');
	$ItemInfo[] = array( name => "Серый домофон", color => '-1');
	$ItemInfo[] = array( name => "Коричневый чемодан", color => '-1');
	$ItemInfo[] = array( name => "Сумка", color => '-1');
	$ItemInfo[] = array( name => "Черная колонка", color => '-1');
	$ItemInfo[] = array( name => "Синий неон", color => '-1');
	$ItemInfo[] = array( name => "Белый неон", color => '-1');
	$ItemInfo[] = array( name => "Розовый неон", color => '-1');
	$ItemInfo[] = array( name => "Желтый неон", color => '-1');
	$ItemInfo[] = array( name => "Зеленый неон", color => '-1');
	$ItemInfo[] = array( name => "Красный неон", color => '-1');
	$ItemInfo[] = array( name => "Танцевальная площадка", color => '-1');
	$ItemInfo[] = array( name => "Скейт", color => '-1');
	$ItemInfo[] = array( name => "Красная гитара", color => '-1');
	$ItemInfo[] = array( name => "Черная гитара", color => '-1');
	$ItemInfo[] = array( name => "Белая гитара", color => '-1');
	$ItemInfo[] = array( name => "Карта штата", color => '-1');
	$ItemInfo[] = array( name => "Флаг", color => '-1');
	$ItemInfo[] = array( name => "Зеленое граффити", color => '-1');
	$ItemInfo[] = array( name => "Оранжевое граффити", color => '-1');
	$ItemInfo[] = array( name => "Фиолетовое граффити", color => '-1');
	$ItemInfo[] = array( name => "Розовое граффити", color => '-1');
	$ItemInfo[] = array( name => "Синее граффити", color => '-1');
	$ItemInfo[] = array( name => "Копье-шокер", color => '-1');
	$ItemInfo[] = array( name => "Модификация Дэдпул (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Киборг (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Елка на плечо", color => '-1');
	$ItemInfo[] = array( name => "Полицейский бронежилет(Улучшение)", color => '-1');
	$ItemInfo[] = array( name => "Домкрат", color => '-1');
	$ItemInfo[] = array( name => "Цевьё (M4)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Ditjey (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Тыква (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Точильный камень", color => '-1');
	$ItemInfo[] = array( name => "Платиновая рулетка", color => '-1');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-3377116');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-1655778');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-2762948');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-12789952');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-12789801');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-12828969');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-2671404');
	$ItemInfo[] = array( name => "Мешок с мясом", color => '-2671490');
	$ItemInfo[] = array( name => "Кирка", color => '-3377116');
	$ItemInfo[] = array( name => "Кирка", color => '-1655778');
	$ItemInfo[] = array( name => "Кирка", color => '-2762948');
	$ItemInfo[] = array( name => "Кирка", color => '-12789952');
	$ItemInfo[] = array( name => "Кирка", color => '-12789801');
	$ItemInfo[] = array( name => "Кирка", color => '-12828969');
	$ItemInfo[] = array( name => "Кирка", color => '-2671404');
	$ItemInfo[] = array( name => "Кирка", color => '-2671490');
	$ItemInfo[] = array( name => "Грабли", color => '-3377116');
	$ItemInfo[] = array( name => "Грабли", color => '-1655778');
	$ItemInfo[] = array( name => "Грабли", color => '-2762948');
	$ItemInfo[] = array( name => "Грабли", color => '-12789952');
	$ItemInfo[] = array( name => "Грабли", color => '-12789801');
	$ItemInfo[] = array( name => "Грабли", color => '-12828969');
	$ItemInfo[] = array( name => "Грабли", color => '-2671404');
	$ItemInfo[] = array( name => "Грабли", color => '-2671490');
	$ItemInfo[] = array( name => "Красный плащ", color => '-1');
	$ItemInfo[] = array( name => "Человек на плечо", color => '-1');
	$ItemInfo[] = array( name => "Уши эльфа", color => '-1');
	$ItemInfo[] = array( name => "Шляпа с красными каплями", color => '-1');
	$ItemInfo[] = array( name => "Ранец охотники на привидений", color => '-1');
	$ItemInfo[] = array( name => "Сумка с сердцами", color => '-1');
	$ItemInfo[] = array( name => "Лопата", color => '-1');
	$ItemInfo[] = array( name => "Лопата", color => '-3398618');
	$ItemInfo[] = array( name => "Лопата", color => '-3377116');
	$ItemInfo[] = array( name => "Лопата", color => '-1655778');
	$ItemInfo[] = array( name => "Лопата", color => '-2762948');
	$ItemInfo[] = array( name => "Лопата", color => '-12789952');
	$ItemInfo[] = array( name => "Лопата", color => '-12789801');
	$ItemInfo[] = array( name => "Лопата", color => '-12828969');
	$ItemInfo[] = array( name => "Лопата", color => '-2671404');
	$ItemInfo[] = array( name => "Лопата", color => '-2671490');
	$ItemInfo[] = array( name => "Скин: Albert (ID: 312)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Amiran (ID: 313)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Bathory (ID: 314)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Brulov (ID: 315)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Egor Creed (ID: 316)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Delorenzy (ID: 317)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Edward Bil (ID: 318)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Eldjey (ID: 319)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Eva Elfie (ID: 320)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Feduk (ID: 321)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Kovalevsky (ID: 322)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Litvin (ID: 323)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Maras Shakur (ID: 324)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Morgershtern (ID: 325)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Habib Nurmagamedov (ID: 326)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Oxymiron (ID: 327)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Pavlenko (ID: 328)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Ravyazan (ID: 329)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Romeru (ID: 330)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Sam Mason (ID: 331)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Diana Shurigina (ID: 332)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Valik (ID: 333)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Basta (ID: 334)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Olga Buzova (ID: 335)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Dzyuba (ID: 336)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Urgant (ID: 337)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Khovansky (ID: 338)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Lukashenko (ID: 339)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Maddison (ID: 340)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Noize (ID: 341)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Pasha Technique (ID: 342)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Restorator (ID: 343)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Richi (ID: 344)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Sasha Grey (ID: 345)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Yury dud (ID: 346)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Snowman (ID: 347)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Elf (ID: 348)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Valik NewYear (ID: 349)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Ded Moroz (ID: 350)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Yoda (ID: 351)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Leshiy (ID: 352)", color => '-1');
	$ItemInfo[] = array( name => "Скин: New shuba (ID: 353)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Deer (ID: 354)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Penguin (ID: 355)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Snegurochka (ID: 356)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Footba (ID: 357)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Elfa (ID: 358)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #1 (ID: 359)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #2 (ID: 360)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #3 (ID: 361)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #4 (ID: 362)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #5 (ID: 363)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Gentelman #6 (ID: 364)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #1 (ID: 365)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #2 (ID: 366)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #3 (ID: 367)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #4 (ID: 368)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #5 (ID: 369)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #6 (ID: 370)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #7 (ID: 371)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #8 (ID: 372)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #9 (ID: 373)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Minecraft #10 (ID: 374)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Navalny #4 (ID: 375)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Putin (ID: 376)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Iron man (ID: 377)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Spiderman (ID: 378)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Venom (ID: 379)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Capitain America (ID: 380)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Batman (ID: 381)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Anonimys (ID: 382)", color => '-1');
	$ItemInfo[] = array( name => "Тайник Илона Маска", color => '-1');
	$ItemInfo[] = array( name => "Ларец Super Car Box", color => '-1');
	$ItemInfo[] = array( name => "Ларец с премией", color => '-1');
	$ItemInfo[] = array( name => "Супер авто-ящик", color => '-1');
	$ItemInfo[] = array( name => "Супер мото-ящик", color => '-1');
	$ItemInfo[] = array( name => "Rare Box Yellow", color => '-1');
	$ItemInfo[] = array( name => "Rare Box Red", color => '-1');
	$ItemInfo[] = array( name => "Rare Box Blue", color => '-1');
	$ItemInfo[] = array( name => "Гражданский талон", color => '-1');
	$ItemInfo[] = array( name => "Видеокарта", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit #1 (ID: 383)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit #2 (ID: 384)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit #3 (ID: 385)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit #4 (ID: 386)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit #5 (ID: 387)", color => '-1');
	$ItemInfo[] = array( name => "Скин: Rabbit Farmer (ID: 388)", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes GT63", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes G63AMG", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Audi RS6", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW X5", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Chevrolet Corvette", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Chevrolet Cruze", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lexus LX", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Porsche 911", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Porsche Cayenne", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Bentley Continental", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW M8", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes E63s", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes S63", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volkswagen Touareg", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lamborghini Urus", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Audi Q8", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Dodge Challenger", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Acura NSX", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volvo V60", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Range Rover evoque", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Honda Civic Type-R", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lexus Sport-S", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Ford Mustang", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volvo XC90", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Jaguar F-pace", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Kia Optima", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW Z4", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes Benz S600", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMX X5 E53", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lexus RX450H", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Ducati Diavel", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Ducati Panigale", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Ducati Ducnaked", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Kawasaki Ninja ZX-10RR", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Western", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Rolls Royce Cullinan", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volkswagen Beetle", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Bugatti Divo", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Bugatti Chiron", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Fiat 2020", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes-Benz GLS", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes G65AMG", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lamborghini Aventador SVJ", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Range Rover SVA", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW 5 Series 530i", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes s600", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Tesla Model X", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Nissan LEAF", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Nissan Silvia S15", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Subaru Forester 2.0XT", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Subaru Legacy RS", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Hyundai Sonata 2020", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW 7 Series E38", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedez Benz E-Class W210", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedez Benz E-Class W124", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Real Tachila", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Molniya Makvin", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Metr", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Buckingham", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Infiniti FX50s", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Lexus RX 450h", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Kia Sportage", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volkswagen Golf R", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Audi R8", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Toyota Camry", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Toyota Camry 3.5", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW M5 E60", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW M5 F90", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes Benz Maybach S650", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mercedes AMG GT R", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Porshe Panamera Turbo", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Volkswagen Passat", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Alpachino (ID: 389)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Bradpitt (ID: 390)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Dicaprio (ID: 391)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Vin Disel (ID: 392)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Kianu (ID: 393)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Ilon Mask (ID: 394)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Robertjr (ID: 395)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Shwarz (ID: 396)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Jason Stethem (ID: 397)", color => '-1');
	$ItemInfo[] = array( name => "Скин:  Tarantino (ID: 398)", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на авто", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на мото", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на полеты", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на плавание", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на ловлю рыбы", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на оружие", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на охоту", color => '-1');
	$ItemInfo[] = array( name => "Лицензия на раскопки", color => '-1');
	$ItemInfo[] = array( name => "Лицензия таксиста", color => '-1');
	$ItemInfo[] = array( name => "Ностальгический ящик", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Aston Martin DB5", color => '-1');
	$ItemInfo[] = array( name => "Сертификат BMW M3 GTR", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Chevrolet Camaro", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mazda RX72", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mazda RX8", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Mitsubishi Eclipse", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Ford Mustang 289", color => '-1');
	$ItemInfo[] = array( name => "Сертификат Nissan 350Z", color => '-1');
	$ItemInfo[] = array( name => "Модификация Химик (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Гринч (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Индеец (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Джетпак #1 (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Джетпак #2 (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Джетпак #3 (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Джетпак #4 (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Купидон (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Пират(модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Призрак (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Волшебник (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Зомби (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Святой Валентин(модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Супер Эльф(модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Рассомаха (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Красные глаза (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Железный Человек (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Дед Мороз (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Тэдди Бирюзовый (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Тэдди Красный (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Тэдди Зеленый (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Сет Демона #2 (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Палач (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Крылья (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Красные крылья (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Модификация Клешни рака (модификация)", color => '-1');
	$ItemInfo[] = array( name => "Рожь (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Морковь (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Картофель (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Лён (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Хлопок (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Пшеница (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Огурцы (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Помидоры (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Белый виноград (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Чай (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Пряные травы (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Канабис (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Кукуруза (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Фиолетовый виноград (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Лечебная трава (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Подсолнух (саженец)", color => '-1');
	$ItemInfo[] = array( name => "Лопата (инструмент)", color => '-1');
	$ItemInfo[] = array( name => "Грабли (инструмент)", color => '-1');
	$ItemInfo[] = array( name => "Ведро (инструмент)", color => '-1');
	$ItemInfo[] = array( name => "Спальник", color => '-1');
	$ItemInfo[] = array( name => "Две палки за спиной", color => '-1');
	$ItemInfo[] = array( name => "Корзина за спиной", color => '-1');
	$ItemInfo[] = array( name => "Техно рюкзак", color => '-1');
	$ItemInfo[] = array( name => "Ядерный рюкзак", color => '-1');
	$ItemInfo[] = array( name => "Копье Зевса", color => '-1');
	$ItemInfo[] = array( name => "Ледяное копье", color => '-1');
	$ItemInfo[] = array( name => "Боеголовка", color => '-1');
	$ItemInfo[] = array( name => "Молнии зевса", color => '-1');
	$ItemInfo[] = array( name => "Шапка Британца", color => '-1');
	$ItemInfo[] = array( name => "Капюшон", color => '-1');
	$ItemInfo[] = array( name => "Рюкзак ученого 1", color => '-1');
	$ItemInfo[] = array( name => "Рюкзак ученого 2", color => '-1');
	$ItemInfo[] = array( name => "Рюкзак для ларьков", color => '-1');
	$ItemInfo[] = array( name => "Инопланетная пушка", color => '-1');
	$ItemInfo[] = array( name => "Маска робота", color => '-1');
	$ItemInfo[] = array( name => "Маска фонарь", color => '-1');
	$ItemInfo[] = array( name => "Красная шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Оранжевая шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Розовая шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Синяя шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Зеленая шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Желтая шляпа маяк", color => '-1');
	$ItemInfo[] = array( name => "Садок", color => '-1');
	$ItemInfo[] = array( name => "Очки переливающиеся", color => '-1');
	$ItemInfo[] = array( name => "Призрачный нимб", color => '-1');
	$ItemInfo[] = array( name => "Усы таракана", color => '-1');
	$ItemInfo[] = array( name => "Щит с шипами", color => '-1');
	$ItemInfo[] = array( name => "Раптор", color => '-1');
	$ItemInfo[] = array( name => "Реактивный ранец", color => '-1');
	$ItemInfo[] = array( name => "Крылья Гаргульи", color => '-1');
	$ItemInfo[] = array( name => "Черная шляпа с шипами", color => '-1');
	$ItemInfo[] = array( name => "Золотая шляпа с шипами", color => '-1');
	$ItemInfo[] = array( name => "Бандитский респект", color => '-1');
	$ItemInfo[] = array( name => "Дильфин на спину", color => '-1');
	$ItemInfo[] = array( name => "Одежда из секонд-хенда", color => '-1');
	$ItemInfo[] = array( name => "Черепаха на спину", color => '-1');
	$ItemInfo[] = array( name => "НЛО на плечо", color => '-1');
	$ItemInfo[] = array( name => "Черная маска", color => '-1');